#!/bin/sh

# script/setup: Resolve all dependencies that the application requires to
#                   run.

main(){
    chmod +x script/config

    . ./script/bootstrap

    printf '\n\e[0;1m bootstrapping the python project\n\e[0m'
    printf ' -------------------------------- \n'

    python3 -m script.bootstrap

    printf '\n\e[0;1m additional configuration \n\e[0m'
    printf ' ------------------------ \n'

    script/config
}

main "$@"
